# Usage:
#   cd speech2text
#   pip3 install .
#   cd ..
#   python3 -m joeynmt train config/speech.yaml

name: "speech_recognition"

type: "audio"

data:
    src: "src"
    trg: "trg"
    # Paths are all the same
    train: "data"
    dev: "data"
    test: "data"
    level: "char"
    lowercase: True
    max_sent_length: 75
    src_voc_min_freq: 0
    src_voc_limit: 100
    trg_voc_min_freq: 0
    trg_voc_limit: 100

testing:
    beam_size: 1
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    learning_rate: 0.001
    learning_rate_min: 0.0002
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 10
    batch_type: "sentence"
    scheduling: "plateau"
    patience: 5
    decrease_factor: 0.5
    early_stopping_metric: "eval_metric"
    epochs: 15
    validation_freq: 1000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "speech_model"
    overwrite: True
    shuffle: True
    use_cuda: False
    max_output_length: 75
    print_valid_sents: [0, 3, 6]
    keep_last_ckpts: 2

model:
    initializer: "xavier"
    embed_initializer: "normal"
    embed_init_weight: 0.1
    bias_initializer: "zeros"
    init_rnn_orthogonal: False
    lstm_forget_gate: 0.
    encoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 256
            scale: False
        hidden_size: 64
        bidirectional: True
        dropout: 0.2
        num_layers: 4
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 256
            scale: False
        hidden_size: 512
        dropout: 0.2
        hidden_dropout: 0.2
        num_layers: 4
        input_feeding: True
        init_hidden: "zero"
        attention: "bahdanau"
